---
title: "Tidy-week7"
author: "Xingnuo Zhang"
date: "4/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data}
tuesdata <- tidytuesdayR::tt_load('2021-02-09')
tuesdata <- tidytuesdayR::tt_load(2021, week = 7)
lifetime_earn <- tuesdata$lifetime_earn
income_distribution <- tuesdata$income_distribution
race_wealth <- tuesdata$race_wealth
income_mean <- tuesdata$income_mean
```
```{r package}
library(tidyverse)
library(viridis)
#install.packages("hrbrthemes")
library(hrbrthemes)
#install.packages("gganimate")
library(gganimate)
```

```{r plot1}
income_mean$income_quintile_f <- factor(income_mean$income_quintile,
                                             levels = c("Top 5%", "Highest", "Second", "Middle", "Fourth","Lowest"))
income_mean %>%
  filter(year > 1996 & 
           race == c('White Alone','Black Alone','Hispanic','Asian Alone', 'All Races') &
           dollar_type == 'Current Dollars') %>%
  ggplot(aes(x = year,y = income_dollars, colour = race)) +
  geom_line(method = "lm", formula = 'y~x') +
  scale_y_continuous() +
  facet_grid(income_quintile_f ~ race, scales = "free") +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = "Year", 
       y = "Total",
       title = "Mean Income Trend of Different Races during 1996-2016",
       caption = str_c("Created by: Xingnuo Zhang, U of T\n",
       "Data source: Urban Institute & US Census"))
```

